[general]
import = ["/home/mroavi/.config/alacritty/colors/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGSDZ Nerd FontMono"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;13~"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;87~"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;83~"
key = "S"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;86~"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;74~"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;75~"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;72~"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;76~"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "LBracket"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mode = "Vi|~Search"

[window]
decorations = "none"
opacity = 0.90
startup_mode = "Maximized" # no effect on systems using DWM

[window.padding]
x = 8
y = 16

[window.dimensions]
columns = 140 # no effect on systems using DWM
lines = 40 # no effect on systems using DWM
