#!/bin/sh

# Save current directory
currentdir="$PWD"

# -----------------------------------------------------------------------------------------
echo "Installing vim plugins..."
# TODO when vim is run for the first time, all the plugins are cloned and installed

# -----------------------------------------------------------------------------------------
echo "Installing zsh..."
sudo apt install zsh

## Build locally (needed when root access is not available)
## https://stackoverflow.com/a/15293565/1706778
#mkdir -p ~/downloads && cd downloads
#wget -O zsh.tar.xz https://sourceforge.net/projects/zsh/files/latest/download
#mkdir zsh && unxz zsh.tar.xz && tar -xvf zsh.tar -C zsh --strip-components 1
#cd zsh
#./configure --prefix=$HOME/local
#make
#make install

# -----------------------------------------------------------------------------------------
echo "Installing oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# -----------------------------------------------------------------------------------------
echo "Installing Powerlevel10k (or pulling if repo already exists)..."
# Add powerlevel10k to the list of Oh My Zsh themes.
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k 2> /dev/null || git -C $ZSH_CUSTOM/themes/powerlevel10k pull

# -----------------------------------------------------------------------------------------
echo "Installing Fonts..."
# See installed mono fonts:
# fc-list :scalable=true:spacing=mono: family

mkdir -p ~/.local/share/fonts && cd ~/.local/share/fonts

# Hack Nerd Font
# https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts
filepath=Hack-for-Powerline-Nerd-Font-regular-complete.ttf
[ -f $filepath ] || curl -fLo "$filepath" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
filepath=Hack-for-Powerline-Nerd-Font-bold-complete.ttf
[ -f $filepath ] || curl -fLo "$filepath" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf
filepath=Hack-for-Powerline-Nerd-Font-italic-complete.ttf
[ -f $filepath ] || curl -fLo "$filepath" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf
filepath=Hack-for-Powerline-Nerd-Font-bold-italic-complete.ttf
[ -f $filepath ] || curl -fLo "$filepath" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf

# Awesome Terminal font
# https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched
filepath=Droid-Sans-Mono-Awesome.ttf
[ -f $filepath ] || curl -fLo "$filepath" https://github.com/gabrielelana/awesome-terminal-fonts/raw/patching-strategy/patched/Droid%2BSans%2BMono%2BAwesome.ttf

# -----------------------------------------------------------------------------------------
echo "Installing clangd and YouCompleteMe..."

sudo apt-get install clangd-9
sudo apt install build-essential cmake python3-dev
#cd ~/.vim/plugged/YouCompleteMe
#python3 install.py --clangd-completer

# -----------------------------------------------------------------------------------------
# https://github.com/BurntSushi/ripgrep#installation
echo "Installing ripgrep..."

# Install if not already installed
# https://stackoverflow.com/a/54239534/1706778
cd /tmp
pkg='ripgrep'
if ! dpkg -s $pkg >/dev/null 2>&1; then
    sudo curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
    sudo dpkg -i ripgrep_11.0.2_amd64.deb
else
    echo "$pkg is already installed"
fi

# -----------------------------------------------------------------------------------------
# https://computingforgeeks.com/bat-cat-command-with-syntax-highlighting-and-git-integration/
echo "Installing bat..."
#sudo apt-get install wget

# https://stackoverflow.com/a/54239534/1706778
pkg='bat'
if ! dpkg -s $pkg >/dev/null 2>&1; then
    export VER="0.13.0"
    wget https://github.com/sharkdp/bat/releases/download/v${VER}/bat_${VER}_amd64.deb
    sudo dpkg -i bat_${VER}_amd64.deb
else
    echo "$pkg is already installed"
fi

# -----------------------------------------------------------------------------------------
# https://github.com/chriskempson/base16-shell
echo "Installing base16-shell..."

git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

## -----------------------------------------------------------------------------------------
# https://github.com/wting/autojump
echo "Installing autojump..."

FILE=$HOME/.autojump/bin/autojump
if [ -f "$FILE" ]; then
    echo "autojump is already installed"
else 
    mkdir -p ~/temp && cd ~/temp
    [ -f ./autojump ] || git clone git://github.com/wting/autojump.git 
    cd autojump
    ./install.py
fi

# -----------------------------------------------------------------------------------------
# Return to original directory
cd "$currentdir"

# TODO: install xclip
