#!/bin/bash

# Save current directory
currentdir="$PWD"

sudo -v # give sudo privileges ahead of time, so that we hopefully only have to enter a password once

# Ensure these dirs exist
mkdir -p ~/.local
mkdir -p ~/Downloads
mkdir -p ~/repos

apt_pkgs_base=(
          wget
          zip
          unzip
          tar
          xclip
          stow
          alacritty
          python3
          python3-venv
          neovim
          zsh
          zsh-autosuggestions
          zsh-syntax-highlighting
          ripgrep
          fzf
          #delta
          fd-find
          zoxide
         )


apt_pkgs_extra=(
          #openssh
          npm
          golang-go
          #dmenu
          #thunar
          #viewnior
          inkscape
          #gimp
          #pavucontrol
          #feh
          #xbindkeys
          #flameshot
          #pipewire
          #pipewire-audio
          #pipewire-alsa
          #pipewire-pulse
          #bluez
          #bluez-utils
          #xf86-input-libinput     # configure touchpad
          #lxappearance            # manage GTK themes
          #qt5ct                   # mange QT themes
          #kvantum
          #okular
          #dunst
          #bottom
          #arandr
          #pkgfile                 # find packages that hold a file (even if the package is not installed)
          #texlive-full            # NOTE: temporarily disabled due to high disk space usage
          #noto-fonts
          #noto-fonts-cjk
          #noto-fonts-emoji
          #noto-fonts-extra
         )

sudo apt install ${apt_pkgs_base[@]}
#sudo apt install ${apt_pkgs_extra[@]}

# pure
echo "Installing pure..."
mkdir -p ~/.zsh
LOCAL_REPO=$HOME/.zsh/pure
REPO_URL=https://github.com/mroavi/pure.git
git clone "$REPO_URL" "$LOCAL_REPO" 2> /dev/null || git -C "$LOCAL_REPO" pull

# julia (uses juliaup)
echo "Installing julia..."
curl -fsSL https://install.julialang.org | sh

# # Make zsh the default shell
# chsh -s $(which zsh)

# Return to original directory
cd "$currentdir"
