#!/bin/bash

# Save current directory
currentdir="$PWD"

sudo -v # give sudo privileges ahead of time, so that we hopefully only have to enter a password once

# Ensure these dirs exist
mkdir -p ~/.local
mkdir -p ~/Downloads
mkdir -p ~/repos

apt_pkgs_base=(
          rofi
          dotnet-runtime-8.0
          dotnet-sdk-8.0
          build-essential
          wget
          curl
          zip
          unzip
          tar
          xclip
          stow
          alacritty
          python3
          python3-pip
          python3-venv
          python3-pynvim
          libfuse2
          npm             # required to install several neovim lsps
          zsh
          zsh-autosuggestions
          zsh-syntax-highlighting
          ripgrep
          fzf
          #delta
          fd-find
          fontconfig      # required to install meslo font family
          zoxide
         )


apt_pkgs_extra=(
          #openssh
          golang-go
          #dmenu
          #thunar
          #viewnior
          inkscape
          #gimp
          #pavucontrol
          #feh
          #xbindkeys
          #flameshot
          #pipewire
          #pipewire-audio
          #pipewire-alsa
          #pipewire-pulse
          #bluez
          #bluez-utils
          #xf86-input-libinput     # configure touchpad
          #lxappearance            # manage GTK themes
          #qt5ct                   # mange QT themes
          #kvantum
          #okular
          #dunst
          #bottom
          #arandr
          #pkgfile                 # find packages that hold a file (even if the package is not installed)
          #texlive-full            # NOTE: temporarily disabled due to high disk space usage
          #noto-fonts
          #noto-fonts-cjk
          #noto-fonts-emoji
          #noto-fonts-extra
         )

sudo apt install ${apt_pkgs_base[@]}
#sudo apt install ${apt_pkgs_extra[@]}

# pure
echo "Installing pure..."
mkdir -p ~/.zsh
LOCAL_REPO=$HOME/.zsh/pure
REPO_URL=https://github.com/mroavi/pure.git
git clone "$REPO_URL" "$LOCAL_REPO" 2> /dev/null || git -C "$LOCAL_REPO" pull

# meslo font family
FILE="$HOME/.local/share/fonts/Meslo LG L Bold Italic Nerd Font Complete Mono.ttf"
if [ -f "$FILE" ]; then
  echo " meslo font family is already installed"
else
  # Source: https://gist.github.com/incogbyte/373f37817742c53891a076391533fe6d
  cd ~
  wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
  mkdir -p .local/share/fonts
  unzip Meslo.zip -d .local/share/fonts
  cd .local/share/fonts
  rm *Windows*
  cd ~
  rm Meslo.zip
  fc-cache -fv
fi

# neovim
echo "Installing nvim..."
# Local installation
# https://github.com/neovim/neovim/wiki/Installing-Neovim#appimage-universal-linux-package
FILE=$HOME/.local/bin/nvim
if [ -f "$FILE" ]; then
  echo " nvim is already installed"
else
  mkdir -p ~/.local/bin && cd ~/.local/bin
  curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
  #curl -LO https://github.com/neovim/neovim/releases/download/v0.7.2/nvim.appimage
  chmod u+x nvim.appimage
  mv nvim.appimage nvim
fi

# Ubuntu/Debian use `fdfind` to avoid conflicts with `fd`.
# Create a symlink for compatibility (fd is used by telescope and fzf).
sudo ln -sf $(which fdfind) /usr/local/bin/fd

# julia (uses juliaup)
#echo "Installing julia..."
#curl -fsSL https://install.julialang.org | sh

# # Make zsh the default shell
# chsh -s $(which zsh)

# Return to original directory
cd "$currentdir"
