# Source:
# https://latexindentpl.readthedocs.io/en/stable/sec-indent-config-and-settings.html

# Paths to user settings for latexindent.pl
#
# Note that the settings will be read in the order you
# specify here- each successive settings file will overwrite
# the variables that you specify

paths:
- /home/mroavi/.config/latexindent/latexindent.yaml
