#!/bin/bash

# Save current directory
currentdir="$PWD"

sudo -v # give sudo privileges ahead of time, so that we hopefully only have to enter a password once

# Ensure these dirs exist
mkdir -p ~/.local
mkdir -p ~/Downloads
mkdir -p ~/repos

# yay
FILE=/usr/bin/yay
if [ -f "$FILE" ]; then
  echo " yay is already installed"
else
  echo "Installing yay..."
  sudo pacman -S --noconfirm --needed git base-devel
  LOCAL_REPO=$HOME/repos/yay
  REPO_URL=https://aur.archlinux.org/yay.git
  git clone "$REPO_URL" "$LOCAL_REPO" 2> /dev/null || git -C "$LOCAL_REPO" pull
  cd $LOCAL_REPO
  makepkg -si
fi

pac_pkgs=(
          alacritty
          autorandr               # auto-detect the connected display hardware and load the appropriate X11 setup using xrandr
          arandr                  # another XRandR GUI
          biber                   # a BibTeX replacement for users of BibLaTeX
          bluez
          bluez-utils
          bottom                  # a graphical process/system monitor for the terminal
          delta
          dmenu
          dotnet-runtime
          dotnet-sdk
          dunst                   # lightweight and customizable notification daemon
          eza
          fd
          feh
          flameshot
          fzf
          fwupd                   # a simple daemon to allow session software to update device firmware on your local machine
          galculator
          gimp
          gnome-keyring
          go
          inkscape
          ipython
          kvantum                 # a Linux SVG-based theme engine for Qt and KDE
          libreoffice-still
          lxappearance            # manage GTK themes
          neovim
          noto-fonts
          noto-fonts-cjk
          noto-fonts-emoji
          noto-fonts-extra
          npm
          okular                  # KDE document viewer
          openssh
          pavucontrol
          picom
          pipewire
          pipewire-alsa
          pipewire-audio
          pipewire-pulse
          pkgfile                 # find packages that hold a file (even if the package is not installed)
          qt5ct                   # mange QT themes
          ripgrep
          sof-firmware            # see: https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#ALSA_firmware
          stow
          tar
          texlive-bibtexextra
          texlive-bin
          texlive-binextra
          texlive-core
          texlive-fontsextra
          texlive-fontutils       # needed by LyX
          texlive-latexextra
          texlive-luatex
          texlive-pictures
          texlive-plaingeneric    # contains 'listofitems.sty'
          texlive-science
          texlive-xetex
          thunar
          tree
          luarocks
          unrar
          unzip
          viewnior                # fast and elegant image viewer
          wget
          xbindkeys
          xclip
          xf86-input-libinput     # configure touchpad
          xournalpp               # handwritten notes
          zip
          zsh
          zsh-autosuggestions
          zsh-syntax-highlighting
          zoxide
         )

yay_pkgs=(
          tmux
          lf
          vidir
          trash-cli
          brave-bin
          git-open
          tio                           # a serial device I/O tool
          ttf-font-awesome-4
          ttf-juliamono
          ttf-meslo-nerd
          ttf-symbola
          catppuccin-gtk-theme-mocha
          kvantum-theme-catppuccin-git
          pistol-git
          pokemon-colorscripts-git
          onedrive-abraunegg      # setup instructions: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md
         )

sudo pacman   -S --noconfirm --needed ${pac_pkgs[@]}
yay           -S --noconfirm --needed ${yay_pkgs[@]}

# dwm
FILE=/usr/local/bin/dwm
if [ -f "$FILE" ]; then
  echo " dwm is already installed"
else
  echo "Installing dwm..."
  sudo pacman -S --noconfirm --needed xorg xorg-server xorg-xinit libx11 libxinerama libxft webkit2gtk
  LOCAL_REPO=$HOME/repos/dwm
  REPO_URL=https://github.com/mroavi/dwm.git
  git clone "$REPO_URL" "$LOCAL_REPO" 2> /dev/null || git -C "$LOCAL_REPO" pull
  cd $LOCAL_REPO
  sudo make clean install
fi

# slock
FILE=/usr/local/bin/slock
if [ -f "$FILE" ]; then
  echo " slock is already installed"
else
  echo "Installing slock..."
  LOCAL_REPO=$HOME/repos/slock
  REPO_URL=https://github.com/mroavi/slock.git
  git clone "$REPO_URL" "$LOCAL_REPO" 2> /dev/null || git -C "$LOCAL_REPO" pull
  cd $LOCAL_REPO
  git checkout mrv
  sudo make clean install
fi

# dwmblocks
FILE=/usr/local/bin/dwmblocks
if [ -f "$FILE" ]; then
  echo " dwmblocks is already installed"
else
  echo "Installing dwmblocks..."
  LOCAL_REPO=$HOME/repos/dwmblocks
  REPO_URL=https://github.com/mroavi/dwmblocks.git
  git clone "$REPO_URL" "$LOCAL_REPO" 2> /dev/null || git -C "$LOCAL_REPO" pull
  cd $LOCAL_REPO
  git checkout mrv
  sudo make clean install
fi

# pure
echo "Installing pure..."
mkdir -p ~/.zsh
LOCAL_REPO=$HOME/.zsh/pure
REPO_URL=https://github.com/mroavi/pure.git
git clone "$REPO_URL" "$LOCAL_REPO" 2> /dev/null || git -C "$LOCAL_REPO" pull

# julia (uses juliaup)
echo "Installing julia..."
curl -fsSL https://install.julialang.org | sh

# # Make zsh the default shell
# chsh -s $(which zsh)

# Create dotfile symlinks with stow
cd ~/dotfiles
stow zsh alacritty git tmux nvim scripts x picom lf xdg vim ssh pistol julia 

# Return to original directory
cd "$currentdir"
